In [1]:
import numpy as np
import pandas as pd

In [2]:
train=pd.read_csv('train.csv')

In [3]:
train.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [4]:
train.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

In [5]:
test=pd.read_csv('test.csv')

In [6]:
test.head()

PassengerId  Pclass                                          Name     Sex  \
0          892       3                              Kelly, Mr. James    male   
1          893       3              Wilkes, Mrs. James (Ellen Needs)  female   
2          894       2                     Myles, Mr. Thomas Francis    male   
3          895       3                              Wirz, Mr. Albert    male   
4          896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female   

    Age  SibSp  Parch   Ticket     Fare Cabin Embarked  
0  34.5      0      0   330911   7.8292   NaN        Q  
1  47.0      1      0   363272   7.0000   NaN        S  
2  62.0      0      0   240276   9.6875   NaN        Q  
3  27.0      0      0   315154   8.6625   NaN        S  
4  22.0      1      1  3101298  12.2875   NaN        S

In [7]:
test.describe()

PassengerId      Pclass         Age       SibSp       Parch        Fare
count   418.000000  418.000000  332.000000  418.000000  418.000000  417.000000
mean   1100.500000    2.265550   30.272590    0.447368    0.392344   35.627188
std     120.810458    0.841838   14.181209    0.896760    0.981429   55.907576
min     892.000000    1.000000    0.170000    0.000000    0.000000    0.000000
25%     996.250000    1.000000   21.000000    0.000000    0.000000    7.895800
50%    1100.500000    3.000000   27.000000    0.000000    0.000000   14.454200
75%    1204.750000    3.000000   39.000000    1.000000    0.000000   31.500000
max    1309.000000    3.000000   76.000000    8.000000    9.000000  512.329200

In [8]:
train['Survived'].value_counts()

0    549
1    342
Name: Survived, dtype: int64

In [9]:
train['Survived'][train.Sex=='male'].value_counts(normalize=True)

0    0.811092
1    0.188908
Name: Survived, dtype: float64

In [10]:
train['Survived'][train.Sex=='female'].value_counts(normalize=True)

1    0.742038
0    0.257962
Name: Survived, dtype: float64

### Feature engineering

First, we use only sex as feature.

In [11]:
train['Sex_enc']=0

In [12]:
train['Sex_enc'][train['Sex']=='male']=0
train['Sex_enc'][train['Sex']=='female']=1

E:\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.
E:\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  


In [13]:
test['Sex_enc']=0

In [14]:
test['Sex_enc'][test['Sex']=='male']=0
test['Sex_enc'][test['Sex']=='female']=1

E:\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.
E:\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  


### Model

In [15]:
from sklearn.linear_model import LogisticRegression

In [16]:
features=train['Sex_enc']
labels=train['Survived']

In [17]:
features=features.values.reshape(-1,1)

In [18]:
clf=LogisticRegression()

In [19]:
clf=clf.fit(features,labels)

E:\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


In [20]:
clf.score(features,labels)

0.7867564534231201

In [21]:
features_test=test['Sex_enc']
features_test=features_test.values.reshape(-1,1)

In [22]:
predictions=clf.predict(features_test)

In [23]:
predictions

array([0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0,
       1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,

In [24]:
test['Survived']=predictions

In [25]:
test[['Sex','Survived']].head()

Sex  Survived
0    male         0
1  female         1
2    male         0
3    male         0
4  female         1

As we see here, it assigns male as 0 and female as 1

In [26]:
submission=test[['PassengerId','Survived']]

In [27]:
submission=submission.set_index('PassengerId')

In [28]:
submission.to_csv('Gender logistic model.csv')

This scored **0.7655** on Kaggle.

### Feature selection


First, let's try choosing all features!

(Replacing Sex with Sex_enc for convenience)

In [29]:
train['Sex']=train['Sex_enc']
test['Sex']=test['Sex_enc']

train=train.drop(columns=['Sex_enc'])
test=test.drop(columns=['Sex_enc'])

In [30]:
train.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name  Sex   Age  SibSp  Parch  \
0                            Braund, Mr. Owen Harris    0  22.0      1      0   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...    1  38.0      1      0   
2                             Heikkinen, Miss. Laina    1  26.0      0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)    1  35.0      1      0   
4                           Allen, Mr. William Henry    0  35.0      0      0   

             Ticket     Fare Cabin Embarked  
0         A/5 21171   7.2500   NaN        S  
1          PC 17599  71.2833   C85        C  
2  STON/O2. 3101282   7.9250   NaN        S  
3            113803  53.1000  C123        S  
4            373450   8.0500   NaN        S

In [31]:
test.head()

PassengerId  Pclass                                          Name  Sex  \
0          892       3                              Kelly, Mr. James    0   
1          893       3              Wilkes, Mrs. James (Ellen Needs)    1   
2          894       2                     Myles, Mr. Thomas Francis    0   
3          895       3                              Wirz, Mr. Albert    0   
4          896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)    1   

    Age  SibSp  Parch   Ticket     Fare Cabin Embarked  Survived  
0  34.5      0      0   330911   7.8292   NaN        Q         0  
1  47.0      1      0   363272   7.0000   NaN        S         1  
2  62.0      0      0   240276   9.6875   NaN        Q         0  
3  27.0      0      0   315154   8.6625   NaN        S         0  
4  22.0      1      1  3101298  12.2875   NaN        S         1

'Embarked' is also categorical, so we need to encode it.

In [32]:
train['Embarked'].value_counts()

S    644
C    168
Q     77
Name: Embarked, dtype: int64

In [33]:
train['Embarked'][train.Embarked=='S']=0
train['Embarked'][train.Embarked=='C']=1
train['Embarked'][train.Embarked=='Q']=2

E:\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.
E:\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  
E:\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until


In [34]:
test['Embarked'][test.Embarked=='S']=0
test['Embarked'][test.Embarked=='C']=1
test['Embarked'][test.Embarked=='Q']=2

E:\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.
E:\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  
E:\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until


In [35]:
train.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name  Sex   Age  SibSp  Parch  \
0                            Braund, Mr. Owen Harris    0  22.0      1      0   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...    1  38.0      1      0   
2                             Heikkinen, Miss. Laina    1  26.0      0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)    1  35.0      1      0   
4                           Allen, Mr. William Henry    0  35.0      0      0   

             Ticket     Fare Cabin Embarked  
0         A/5 21171   7.2500   NaN        0  
1          PC 17599  71.2833   C85        1  
2  STON/O2. 3101282   7.9250   NaN        0  
3            113803  53.1000  C123        0  
4            373450   8.0500   NaN        0

Features that can be used are: Pclass, Sex, Age, SibSp, Parch, Fare, Embarked

Replacing NA's

In [36]:
train.isna().any()

PassengerId    False
Survived       False
Pclass         False
Name           False
Sex            False
Age             True
SibSp          False
Parch          False
Ticket         False
Fare           False
Cabin           True
Embarked        True
dtype: bool

In [37]:
train["Age"] = train["Age"].fillna(train["Age"].median())
train["Embarked"] = train["Age"].fillna('S')

Doing the classification

In [38]:
featureset_multi=['Pclass','Sex','Age','SibSp','Parch','Fare','Embarked']
features_train_multi=train[featureset_multi]

In [39]:
clf=clf.fit(features_train_multi,labels)

E:\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


In [40]:
clf.score(features_train_multi,labels)

0.8002244668911336

In [41]:
test.isna().sum()

PassengerId      0
Pclass           0
Name             0
Sex              0
Age             86
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
Survived         0
dtype: int64

In [42]:
test["Age"] = test["Age"].fillna(test["Age"].median())
test["Fare"] = test["Fare"].fillna(test["Fare"].median())

In [43]:
features_test_multi=test[featureset_multi]

In [44]:
preds_multi=clf.predict(features_test_multi)

In [45]:
test['Survived']=preds_multi

In [46]:
test.head()

PassengerId  Pclass                                          Name  Sex  \
0          892       3                              Kelly, Mr. James    0   
1          893       3              Wilkes, Mrs. James (Ellen Needs)    1   
2          894       2                     Myles, Mr. Thomas Francis    0   
3          895       3                              Wirz, Mr. Albert    0   
4          896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)    1   

    Age  SibSp  Parch   Ticket     Fare Cabin Embarked  Survived  
0  34.5      0      0   330911   7.8292   NaN        2         0  
1  47.0      1      0   363272   7.0000   NaN        0         1  
2  62.0      0      0   240276   9.6875   NaN        2         0  
3  27.0      0      0   315154   8.6625   NaN        0         0  
4  22.0      1      1  3101298  12.2875   NaN        0         1

In [47]:
submission2=test[['PassengerId','Survived']]

In [48]:
submission2=submission2.set_index('PassengerId')

In [49]:
submission2.to_csv('Logistic model (all features).csv')

Kaggle score: **0.71770**

### Selecting Features

We see the coefficients of each of the features.

In [50]:
featureset_multi,clf.coef_

(['Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare', 'Embarked'],
 array([[-0.95811394,  2.64120625, -0.01702727, -0.32722806, -0.09839945,
          0.00389565, -0.01702727]]))

Let's try using 'Sex' and 'Fare'

In [51]:
featureset_3=['Sex','Fare']

In [52]:
features_train_3=train[featureset_3]
features_test_3=test[featureset_3]

In [53]:
clf_3=LogisticRegression().fit(features_train_3,labels)

E:\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


In [54]:
clf_3.score(features_train_3,labels)

0.7822671156004489

In [55]:
clf_3.coef_

array([[2.33590816, 0.01098419]])

Let's also add 'Parch' and 'Embarked' along with that.

In [56]:
featureset_4=featureset_3+['Parch','Embarked']

In [57]:
features_train_4=train[featureset_4]
features_test_4=test[featureset_4]

In [58]:
clf_4=LogisticRegression().fit(features_train_4,labels)

E:\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


In [59]:
clf_4.score(features_train_4,labels)

0.7890011223344556

In [60]:
clf_4.coef_

array([[ 2.45265088,  0.01389529, -0.35532884, -0.01551157]])

Now doing predictions

In [61]:
predictions3=clf_3.predict(features_test_3)

In [62]:
test['Survived']=predictions3

In [63]:
submission3=test[['PassengerId','Survived']]

In [64]:
submission3=submission3.set_index('PassengerId')

In [65]:
submission3.to_csv('Log model two features.csv')

Kaggle score: **0.76076**

In [66]:
predictions4=clf_4.predict(features_test_4)

In [67]:
test['Survived']=predictions4

In [68]:
submission4=test[['PassengerId','Survived']]
submission4=submission4.set_index('PassengerId')
submission4.to_csv('Log model four features.csv')

Kaggle score: **0.75119**

So far, we've seen that logistic regression works best with single feature ('Sex').
Kaggle description says 'Although there was some element of luck involved in surviving the sinking, some groups of people were more likely to survive than others, such as **women, children, and the upper-class.**'

## Revision

In [69]:
train.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name  Sex   Age  SibSp  Parch  \
0                            Braund, Mr. Owen Harris    0  22.0      1      0   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...    1  38.0      1      0   
2                             Heikkinen, Miss. Laina    1  26.0      0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)    1  35.0      1      0   
4                           Allen, Mr. William Henry    0  35.0      0      0   

             Ticket     Fare Cabin  Embarked  
0         A/5 21171   7.2500   NaN      22.0  
1          PC 17599  71.2833   C85      38.0  
2  STON/O2. 3101282   7.9250   NaN      26.0  
3            113803  53.1000  C123      35.0  
4            373450   8.0500   NaN      35.0

In [70]:
train['Child']=0

In [71]:
train['Child'][train['Age']>=18]=0
train['Child'][train['Age']<18]=1

E:\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.
E:\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  


In [72]:
test['Child']=0
test['Child'][test['Age']>=18]=0
test['Child'][test['Age']<18]=1

E:\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  
E:\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until


In [73]:
featureset_5=['Sex','Child','Pclass']

In [74]:
features_train_5=train[featureset_5]
features_test_5=test[featureset_5]

In [75]:
clf_5=LogisticRegression().fit(features_train_5,labels)

E:\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


In [76]:
clf_5.score(features_train_5,labels)

0.7912457912457912

In [77]:
predictions5=clf_5.predict(features_test_5)
test['Survived']=predictions5
submission5=test[['PassengerId','Survived']]
submission5=submission5.set_index('PassengerId')
submission5.to_csv('One engineered feature.csv')

<b>Kaggle Score: 0.7703</b>

In [78]:
clf_5.coef_

array([[ 2.52400189,  0.92540106, -0.98987554]])

Now, we check without Pclass since it gives negative value

In [79]:
featureset_6=['Sex','Child']

In [80]:
features_train_6=train[featureset_6]
features_test_6=test[featureset_6]

In [81]:
clf_6=LogisticRegression().fit(features_train_6,labels)
clf_6.score(features_train_6,labels)

E:\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


0.7867564534231201

In [82]:
clf_6.coef_

array([[2.40882683, 0.50644055]])

In [83]:
predictions6=clf_6.predict(features_test_6)
test['Survived']=predictions6
submission6=test[['PassengerId','Survived']]
submission6=submission6.set_index('PassengerId')
submission6.to_csv('One engineered feature_2.csv')

<B>Kaggle Score: 0.7655</b>

So, the features described by Kaggle's description are the best.

## Using decision trees

Decision trees are another way to perform classification.

In [84]:
from sklearn.tree import DecisionTreeClassifier

First, all features..

In [85]:
features_train_multi.head()

Pclass  Sex   Age  SibSp  Parch     Fare  Embarked
0       3    0  22.0      1      0   7.2500      22.0
1       1    1  38.0      1      0  71.2833      38.0
2       3    1  26.0      0      0   7.9250      26.0
3       1    1  35.0      1      0  53.1000      35.0
4       3    0  35.0      0      0   8.0500      35.0

In [86]:
clf_dt=DecisionTreeClassifier().fit(features_train_multi,labels)

In [89]:
clf_dt.score(features_train_multi,labels)

0.9797979797979798

In [91]:
predictions_dt=clf_dt.predict(features_test_multi)
test['Survived']=predictions_dt
submission_dt=test[['PassengerId','Survived']]
submission_dt=submission_dt.set_index('PassengerId')
submission_dt.to_csv('Decision Tree.csv')

<b>Kaggle Score: 0.38755</b>

Too much overfitting!

In [94]:
featureset_multi

['Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare', 'Embarked']

In [92]:
clf_dt.feature_importances_

array([0.10681611, 0.31088095, 0.09755398, 0.04881046, 0.0244299 ,
       0.26137091, 0.15013769])

Trying to visualize the tree

In [96]:
import graphviz